# .streamlit/config.toml
[theme]
base = "light"
primaryColor = "#E63946"            # detalhe vermelho (foco/hover)
backgroundColor = "#FFFFFF"         # fundo do app (branco)
secondaryBackgroundColor = "#F4F6FB" # fundos de caixas/containers (azul bem claro)
textColor = "#17193B"               # navy text
font = "sans serif"